# Generated by Django 3.2.7 on 2021-09-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='type',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('OWNER', 'Owner')], default='OWNER', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
