# Generated by Django 3.2.7 on 2021-09-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210908_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(default=0.08333333333333333, on_delete=django.db.models.deletion.CASCADE, to='main_app.newuser'),
            preserve_default=False,
        ),
    ]
