# Generated by Django 3.2.7 on 2021-09-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_animal_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='owner',
            new_name='user',
        ),
    ]
