# Generated by Django 3.2.7 on 2021-09-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_owner_animal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='type',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('OWNER', 'Owner')], max_length=50, unique=True, verbose_name='Type'),
        ),
    ]
