# Generated by Django 3.2.7 on 2021-09-09 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_animalphoto_userphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.animal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userphoto',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnimalPhoto',
        ),
        migrations.DeleteModel(
            name='UserPhoto',
        ),
    ]
