# Generated by Django 3.2.7 on 2021-09-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_task_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(default=12, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
