# Generated by Django 3.2.7 on 2021-09-10 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_newuser_first_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
